export { default as product } from './product'
export { default as products } from './products'
export { default as customers } from './customers'
export * as schemas from './schemas'
export { denormalize } from 'normalizr'
