---
extends: commercetools
plugins:
- flowtype
env:
  es6: true
  jest: true
  node: true
rules:
  flowtype/define-flow-type: 1
  flowtype/require-parameter-type: 1
  flowtype/require-return-type:
  - 1
  - always
  - annotateUndefined: never
  flowtype/semi: 0
  flowtype/space-after-type-colon:
  - 1
  - always
  flowtype/space-before-type-colon:
  - 1
  - never
  flowtype/type-id-match: 0
  flowtype/use-flow-type: 1
  flowtype/valid-syntax: 1
  import/no-extraneous-dependencies:
  - error
  - devDependencies:
    - "**/test/**/*.js"
settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true
  import/resolver:
    babel-module: {}
