sudo: false

language: node_js

node_js:
  - 4
  - 6
  - 8

# Reason why we are caching .npm and not node_modules
# https://stackoverflow.com/a/42523517/4151025
cache:
  directories:
    - $HOME/.npm

notifications:
  email: false

before_install:
  - .travis/before_install.sh

script:
  - .travis/scripts.sh

after_success:
  - .travis/after_success.sh

git:
  depth: 5
