sudo: false

language: node_js

node_js:
  - 4
  - 6
  - 8

cache: 'yarn'

notifications:
  email: false

before_install:
  # Trusty images at TravisCI come with an older version of yarn.
  # We want workspace support for lerna and manually update it here.
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - .travis/before_install.sh

script:
  - .travis/scripts.sh

after_success:
  - .travis/after_success.sh

git:
  depth: 5
