sudo: false

language: node_js

node_js:
  - 4
  - 6

cache: 'yarn'

notifications:
  email: false

before_install:
  - .travis/before_install.sh

script:
  - .travis/scripts.sh

after_success:
  - .travis/after_success.sh

git:
  depth: 5
