env:
  global:
    - PATH=$HOME/.yarn/bin:$PATH

sudo: false

language: node_js

node_js:
  - 4
  - 6
  - 8

notifications:
  email: false

before_install:
  - .travis/before_install.sh

cache: 'yarn'

script:
  - .travis/scripts.sh

after_success:
  - .travis/after_success.sh

git:
  depth: 5
