export const query = 'query'
export const queryOne = 'queryOne'
export const queryExpand = 'queryExpand'
export const queryLocation = 'queryLocation'
export const search = 'search'
export const projection = 'projection'
export const suggest = 'suggest'
