name: CI

description: Shared action to install dependencies

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4.1.0
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"

    # Whenever on a changeset versioning PR
    # Then installing con not fail with lockfile changes
    # Because the package.json for integration test changes.

    - name: Install
      run: pnpm install --no-frozen-lockfile
      shell: bash
