#!/bin/bash -e

tars=()

echo "--> Pack all packages:"
for dir in packages/*; do
  echo "$dir"
  pushd "$dir" > /dev/null
  tarName=$(npm pack)
  tars=("${tars[@]}" "$(pwd)/${tarName}")
  popd > /dev/null
done

# Fix issues with failing installation due to polyfills in graceful-fs package
curl -XGET 'https://raw.githubusercontent.com/isaacs/node-graceful-fs/168bdb8f0bb3174e8499d4bc5878deead4172c39/polyfills.js' > node_modules/npm/node_modules/graceful-fs/polyfills.js

echo "--> Install dependencies and packages for integration-tests:"
pushd "./integration-tests" > /dev/null
npm i "${tars[@]}" --no-save --no-package-lock
npm i --no-package-lock
popd > /dev/null

echo "--> Cleanup tarballs"
for tar in "${tars[@]}"; do
  rm "${tar}"
done
