#!/bin/bash -e

tars=()

echo "Using NPM and Node.js versions:"
npm -v
node -v

echo "--> Pack all packages:"
for dir in packages/*; do
  echo "$dir"
  pushd "$dir" > /dev/null
  tarName=$(npm pack)
  tars=("${tars[@]}" "$(pwd)/${tarName}")
  popd > /dev/null
done

echo "--> Install dependencies and packages for integration-tests:"
pushd "./integration-tests" > /dev/null
npm i "${tars[@]}" --no-save --no-package-lock
npm i --no-package-lock
popd > /dev/null

echo "--> Cleanup tarballs"
for tar in "${tars[@]}"; do
  rm "${tar}"
done
