#!/bin/bash -e

# Lints staged js-files

# find staged files which end in ".js"
# eslint will exclude the ones ignored by .eslintignore even if we pass them
# explicitly
set +e
FILES="$(git diff --cached --name-only --diff-filter=ACM | grep '\.js$')"
set -e

# If grep didn't find any match (fails), simply exit
if [ $? -eq 1 ]; then
  exit 0
fi

# If there are matching files, lint them
if [ -n "$FILES" ]; then
  # lint these files
  ./scripts/lint $FILES
fi
