#!/bin/bash -e

read -p "Username: " username

for f in packages/*; do
  package=`basename $f`
  npm_package="@commercetools/$package"

  if [ -d "$f" ]; then
    npm owner add $username $npm_package
  fi
done
