#!/bin/bash -e

read -p "Username: " username

for f in packages/*; do
  package=`basename $f`
  npm_package="${package/commercetools-/@commercetools/}"

  if [ -d "$f" ]; then
    npm owner rm $username $npm_package
  fi
done
