#!/bin/bash

cd dist

regions=($(./aws.sh ec2 describe-regions --query "Regions[].{Name:RegionName}" --output text --region="eu-central-1"))

for region in "${regions[@]}"
do
    echo "Uploading to $region"

    version=$(./aws.sh lambda publish-layer-version --layer-name commercetools-nodejs-sdk --description "commercetools' node.js SDK" --license-info "MIT" --zip-file fileb://commercetools-nodejs-sdk.zip --compatible-runtimes nodejs6.10 nodejs8.10 --region="$region" --query 'Version')

    ./aws.sh lambda add-layer-version-permission --layer-name commercetools-nodejs-sdk --statement-id engineering-org --version-number $version --principal '*' --action lambda:GetLayerVersion --region="$region" > /dev/null
done