#!/bin/bash -e

# Ensure we are running in root directory
if [ "$(basename $(pwd))" != 'nodejs' ]; then
  echo "Error: Run script in monorepo root directory with folder name 'nodejs'"
  exit 1
fi

packages=()
for dir in packages/*; do
  packages=(${packages[@]} "${dir/packages\//@commercetools/}")
done

echo "Select a package to publish to npm:"
select package in "${packages[@]}"; do
  selected_package=$package
  echo "Selected package $selected_package"
  break
done

# Strip the '@commercetools/' in front of the package name
selected_package=${selected_package:15}

rootPathGit="$(pwd)/.git"
packagePathGit="$(pwd)/packages/$selected_package/.git"
packagePath="./packages/$selected_package"
echo "packPG $packagePathGit"

# Link root git folder to package folder
ln -sf $rootPathGit $packagePathGit

# Run the publish script
npm publish $packagePath --access public

# Remove the link created on line 30
unlink $packagePathGit

echo "Package $selected_package published"
