#!/bin/bash -e

# The package name where the tests should run
package="${1}"
# An optiona flag to pass to the test runner (see validation below)
flag="${2}"

if [ -z "$package" ]; then
  echo "Missing required package name"
  exit 1
fi

if [ -n "$flag" ]; then
  if [[ "$flag" != "--watch" && "$flag" != "--coverage" ]]; then
    echo "Only --watch or --coverage mode are supported as flag"
    exit 1
  fi
fi

# Path to jest executable
cmd="$(pwd)/node_modules/.bin/jest"

pushd "./packages/${package}"
if [ -z "$flag" ]; then
  eval "$cmd"
else
  eval "$cmd $flag"
fi
popd
