#!/bin/bash -e

# An optional flag to pass to the test runner (see validation below)
flag="${1}"

if [ -n "$flag" ]; then
  if [[ "$flag" != "--watch" && "$flag" != "--coverage" ]]; then
    echo "Only --watch or --coverage mode are supported as flag"
    exit 1
  fi
fi

packages=()
for dir in packages/*; do
  packages=(${packages[@]} "${dir/packages\/commercetools-/@commercetools/}")
done

select package in "${packages[@]}"; do
  selected_package=$package
  echo "Selected package $selected_package"
  break
done

if [ -z "$flag" ]; then
  $(npm bin)/lerna --scope $selected_package exec -- $(pwd)/node_modules/.bin/jest
else
  $(npm bin)/lerna --scope $selected_package exec -- $(pwd)/node_modules/.bin/jest $flag
fi
