name: Quality

on:
  push:
    branches:
      - 'master'
      - '!changeset-release/**'
  pull_request:

jobs:
  lockfile:
    if: ${{ !startsWith(github.ref, 'refs/heads/changeset-release/') }}
    name: Lockfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/ci

      # The shared install action does not respect the
      # `--frozen-lockfile` flag, so we need to run it here.
      - name: Install with lockfile
        run: pnpm install --frozen-lockfile

  linting:
    if: ${{ !startsWith(github.ref, 'refs/heads/changeset-release/') }}
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/ci

      # Needed for ESLint as otherwise imports are not resolved
      - name: Build CLIs
        run: pnpm build:clis

      - name: Lint
        run: pnpm lint

  type-checking:
    if: ${{ !startsWith(github.ref, 'refs/heads/changeset-release/') }}
    name: Type checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/ci

      - name: TypeScript
        run: pnpm typecheck:ts

      - name: Flow
        run: pnpm typecheck:flow

  testing:
    if: ${{ !startsWith(github.ref, 'refs/heads/changeset-release/') }}
    name: Testing
    needs: [lockfile, linting, type-checking]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/ci

      - name: Build
        run: pnpm build

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Test (with coverage)
        run: pnpm test:coverage:ci

      - name: Integration tests
        run: pnpm test:integration

  regression-testing:
    if: ${{ !startsWith(github.ref, 'refs/heads/changeset-release/') }}
    name: Regression Testing
    needs: [testing]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [18, 20]
      fail-fast: true
      max-parallel: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/ci

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: Build
        run: pnpm build

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Integration tests
        run: pnpm test:integration
