name: Regression

on:
  workflow_run:
    workflows: [Quality]
    types:
      - completed

jobs:
  testing:
    name: Regression Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [18, 20]
      fail-fast: true
      max-parallel: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/ci

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: Build
        run: pnpm build

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Test (with coverage)
        run: pnpm test:coverage:ci

      - name: Integration tests
        run: pnpm test:integration
